### ISSUE TITLE
Provide example of configuration

### ISSUE THREAD

**Issue by hawkins** [codealchemist/hyper-transparent#1]
I can't figure out how we're supposed to configure the default transparency for this plugin.

Is it a custom `~/hyper-transparent.json` file? Or a `backgroundColor` property in `~/.hyper.json`?

Could you please provide an example of configuring this plugin or elaborate on instructions to do so?

**Comment by Toinane** [comment]
It will be great if we can change the default color, I don't like black #000 but #303747 for example

**Comment by codealchemist** [comment]
It doesn't currently support changing colors, but that's a good idea!
I'll look into it.

Thanks for your feedback guys!

**Comment by hawkins** [comment]
Hey @codealchemist, Could you please provide a demonstration for configuration though so we can use this without having to manually set the transparency every time we open a new window of hyper?

**Comment by codealchemist** [comment]
@hawkins I'm Hyper v0.8.3 and set transparency is applied to all new windows automatically.
Which version are you using?
I'll update Hyper to see what happens.

About configuration:
Currently, the only way to configure the plugin is to go inside the plugins folder and edit its config there.

Look for:
`~/.hyper_plugins/node_modules/hyper-transparent/hyper-transparent.json`

There you have:
`{"backgroundColor":"rgba(0,0,0,0.5)"}`

Which is the only config available at this time.

Also, is there anything else you would you like to configure besides background color?
Thanks!

**Comment by codealchemist** [comment]
Note: You can change the color in the config file, but...
If you later set another transparency option from the app menu it will default to black again.
If you guys think it's useful to change background color and transparency I'll look into providing support for it.

Cheers!

**Comment by codealchemist** [comment]
I just published a new version of the plugin with support to preserve the background color you set in the config file.
The format still needs to be `rgba` for it to work.
But now it will change the transparency layer only.

![image](https://cloud.githubusercontent.com/assets/1118293/26751048/d8efc13e-4806-11e7-94cb-4607d23dfa4d.png)

Probably not as good as being able to set background color from the app with a color picker, but while we wait for something better it gets the job done.

Please, let me know if this works for you.
Cheers!

**Comment by codealchemist** [comment]
One way of **updating** the plugin is going to the plugins folder:
`~/.hyper_plugins`

And run:
`npm install --save hyper-transparent`

**Comment by codealchemist** [comment]
Just checked with latest version of Hyper.
Working fine.

![image](https://cloud.githubusercontent.com/assets/1118293/26753880/92c9e118-4846-11e7-8a40-f447ddf746bb.png)

**Comment by hawkins** [comment]
Thanks! Might be useful to add that note about config to the README, but this works for me. Thanks for the clarifications - closing this :)

**Comment by codealchemist** [comment]
Hey guys, I just released a new version with an updated readme and support for vibrancy, which is a pretty cool visual property we can set on OSX.

Please, let me know how that works for you.
:)

Cheers!

**Comment by Toinane** [comment]
Thanks! It's useful! :) I like vibrancy on OSX
