### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by joggienl** [codealchemist/hyper-transparent#11]
I currently run into the problem that every time I (re)open hyper, my previous setting for hyper-transparent is being discarded. Putting it in the .json file is also not working well, if hyper looks for updates, the value get's overridden again.

So, I would like to opt for being able to set configuration in the only place it makes sense: the ~/.hyper.js file. Changing the underlying node_modules files is either way bad practice.

Brings me to my next point, how active is this project? @codealchemist do you still have time to update/refactor? Do you accept PR's? There are more issues regarding this and I'm curious to your position in this.

Thanks!

**Comment by codealchemist** [comment]
Hi @joggienl!
I can work from time to time on this project.
Willing to accept PRs :)

**Comment by codealchemist** [comment]
That's a really fair point about config.
If you create a PR to set the config on Hyper's main config file or create another custom config file for hyper-transparent on the user's home folder I will gladly merge it.

Thanks!

**Comment by codealchemist** [comment]
Hey @joggienl, please check version 1.2.0.
It allows setting a default config on `.hyper.js` main config file.
This should address this issue.

Cheers!
