### ISSUE TITLE
hyperTransparent not fully taking effect

### ISSUE THREAD

**Issue by dk0r** [codealchemist/hyper-transparent#18]
**Issue**: hyperTransparent's `opacity` setting (which is defined in `.hyper.js`) is not reapplied after `hyper@2.0.0` is restarted on `macOS@10.13.6`. For reference, here is my full config ==> [.hyper.js](https://gist.github.com/dk0r/b3ef6c581211424abcf28298c738189d)

**Steps to Reproduce**: 
1. Uninstall hyper
2. Remove prior configs/plugins: 
`rm -r ~/.hyper.js ~/.hyper_plugins`
3. Reinstall from [https://hyper.is/#installation](https://hyper.is/#installation)
4. Referencing the [docs](https://www.npmjs.com/package/hyper-transparent#set-default-config), add 'hyper-transparent' to plugins section of `.hyper.js`:
`  plugins: [
   'hyper-transparent'
  ],`
5. Quit & Start hyper
6. Add 'hyperTransparent' settings to `.hyper.js` config:
```
module.exports = {
  config: {

    hyperTransparent: {
      backgroundColor: '#4b4',
      opacity: 0.2,
      vibrancy: '' // ['', 'dark', 'medium-light', 'ultra-dark']
    },
```
7. Notice upon saving in Step-4 that the new `hyperTransparent` settings have taken effect.
8. Quit & Start Hyper
9. Notice that `hyperTransparent`'s `backgroundColor` is set but the `opacity` is not.

**Steps to Resolve**:
1. With hyper already open, open `.hyper.js` and resave it.
2. Notice that the `hyperTransparent`'s `opacity` setting has taken effect

**Comment by codealchemist** [comment]
Hi!
Thanks for reporting this!

After adding `hyper-transparent` to plugins array do you wait until the plugin update completes before restarting?

I wasn't able to reproduce it so far.

**Comment by neo-anderson** [comment]
This is occurring on my end as well. opacity setting worked once. Since then, it has no effect, no matter what value I set.

**Comment by codealchemist** [comment]
Oh, yeah!
When vibrancy is on, the transparency effect works differently.
I wasn't able to figure out a way to make vibrant windows more transparent.
Sorry guys!


If you still want this feature maybe we can create a feature request and try to get help from the community. If someone else knows how to do this I will gladly merge a PR with this enhancement.

Thanks!
