### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by imfatant** [codealchemist/hyper-transparent#21]
Win 10 x64
transparency doesn't work

**Comment by AlbertoMiranda-minted** [comment]
I wonder if it might be related to this:
https://github.com/zeit/hyper/blob/41b1ac1852bec5e34a61c897a4b262073aa996a7/app/ui/window.ts#L36

I'll try to get some time to test on Windows.

**Comment by codealchemist** [comment]
Let's follow up on #4 
Thx!
