### ISSUE TITLE
Vibrancy causes square window corners on 10.13

### ISSUE THREAD

**Issue by purrloftruth** [codealchemist/hyper-transparent#8]
Hi there! Thanks for your great plugin. I'm just starting to use Hyper, and I love `hyper-transparent`'s vibrancy settings.

Unfortunately, using them on 10.13 results in some weirdness with the window corners.

[![Visual demonstration of issue](https://thumbs.gfycat.com/AfraidInnocentBagworm-size_restricted.gif)](https://gfycat.com/AfraidInnocentBagworm)
*click to view larger*

As you can see, when using any vibrancy setting, the window corners appear square. When turning off vibrancy, the window corners return to their normal rounded state.

I just upgraded to High Sierra last night and don't recall ever observing this behavior while I was using this plugin on 10.12.6. I can also confirm that this behavior occurs on a fresh hyper.js file with hyper-transparent as the only plugin loaded.

Thanks again for your great plugin, and please keep up the great work! I hope you and your families at home and at work are happy and well.

**Comment by kieranju** [comment]
Sadly, the native terminal app also experiences similar visual glitches when setting a blur amount higher than 0. 

Not sure how one would handle this cleanly, but I can at least help verify this only started happening as of updating to 10.13 from 10.12.6.

**Comment by crownsedge** [comment]
I see what you mean. In that case, it doesn’t square the corners, instead looking like it’s over-sharpening or over-contracting the edges of the window. Strange behavior. Would file a radar, but I don’t currently have an active developer subscription. :pensive:

On Sep 27, 2017, at 3:09 PM, Kieran Utz <notifications@github.com<mailto:notifications@github.com>> wrote:


Sadly, the native terminal app also experiences similar visual glitches when setting a blur amount higher than 0.

Not sure how one would handle this cleanly, but I can at least help verify this only started happening as of updating to 10.13 from 10.12.6.

**Comment by codealchemist** [comment]
Hi!
I think we can close this one, it looks like something we won't be able to fix on the plugin side.


Thx!
