### ISSUE TITLE
Color settings erased in hyper-trasnparent.json

### ISSUE THREAD

**Issue by 2hands10fingers** [codealchemist/hyper-transparent#9]
Hello,

Tried using this. The RGB color channels keep getting erased once I change the transparency.

Hyper 1.4.8
hyper-transparent 1.1.1
Mac OSX

**Comment by codealchemist** [comment]
Fixed on #12.
Thanks for reporting it!
:)

**Comment by codealchemist** [comment]
Just published `hyper-transparent@1.1.5`.
